modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/henkelmax/sleeping-bags/issues"
[[mods]]
modId="sleeping_bags"
version="${mod_version}"
displayName="Sleeping Bags"
updateJSONURL="https://update.maxhenkel.de/neoforge/sleeping_bags"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sleeping-bags"
logoFile = "icon.png"
authors="Max Henkel"
description='''Sleeping bags'''
[[dependencies.sleeping_bags]]
    modId="neoforge"
    mandatory=true
    versionRange="${neoforge_dependency}"
    ordering="NONE"
    side="BOTH"
[[dependencies.sleeping_bags]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"